AWSTemplateFormatVersion:  2010-09-09

Resources:
  Application:
    Type:                "AWS::EC2::Instance"
    Description:         "EC2 instance"
    Properties:
      InstanceType:      t3.medium
      SubnetId:          enter subnet id
      ImageId:           enter image id
      AvailabilityZone:  enter region
      SecurityGroupIds:
        - enter security group id
      UserData:
        Fn::Base64:    !Sub |
          #!/bin/bash

          ENVIRONMENT_NAME=${ENVIRONMENTNAME}
          INSTANCE_TYPE=Application

          cd /tmp
          echo "$(date) - building $INSTANCE_TYPE for $ENVIRONMENT_NAME" >> /var/log/build.log
          git clone -b $ENVIRONMENT_NAME git@bitbucket-url/cloudformation-template.git
          cd cloudformation-template
          ./build $INSTANCE_TYPE
      Tags:
        - Key: Name
          Value: !Sub |
            SL ${VERSION} ${ENVIRONMENTNAME} Application

Parameters:
  ENVIRONMENTNAME:
    Type:                  String
    Default:               Dev
    Description:           one of Dev, QA, Staging, Pilot or Production
    AllowedValues:
      - Dev
      - QA
      - Staging
      - Pilot
      - Production
  VERSION:
    Type:                  String
    Default:               snapshot
    Description:           version of the web platform to deploy