version: 0.0
os: linux
files:
  - source: /target/application-0.0.1-SNAPSHOT.jar
    destination: /opt/application/
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/remove_archives.sh
    - location: scripts/stop_server
      timeout: 300
      runas: root